### ISSUE TITLE
Renaming a project folder stops it opening

### ISSUE THREAD

**Issue by DuffleOne** [getbeak/beak#216]
Type: Bug
Platform: macOS Silicon

As a user, I want to be able to change my Beak project name. I changed my folder name and now it won't open anymore. Was named "dfl", renamed to "beak-dfl". I updated the project.json file too, still won't open.

[beak-dfl.zip](https://github.com/getbeak/beak/files/7576060/beak-dfl.zip)

**Comment by 0xdeafcafe** [comment]
This will be fixed in `v1.0.6` 👍
