### ISSUE TITLE
Unknown HTTP status code

### ISSUE THREAD

**Issue by DuffleOne** [getbeak/beak#223]
Type: Feature request
Platform: macOS Silicon

![img](https://dfl.mn/Xkj)

Would be handy if I could see the HTTP status code somewhere here.

**Comment by billinghamj** [comment]
This one doesn't have a status code I don't think - it failed before getting to the point of doing HTTP stuff

**Comment by 0xdeafcafe** [comment]
Have added an error view to make this a little clearer

![Screenshot 2021-12-17 at 21 14 35](https://user-images.githubusercontent.com/2768524/146608843-6c2bf826-39d1-4b70-9f8e-3fc54d24026f.png)
