### ISSUE TITLE
Make the JSON enriched response view configurable

### ISSUE THREAD

**Issue by DuffleOne** [getbeak/beak#62]
Type: Feature request
Platform: N/A

As a user, I'd love to be able to make the JSON enriched view have larger text for my tiny eyes. And make it have colours for nested JSON.

**Comment by 0xdeafcafe** [comment]
The font size deffo should be configurable, I will add that when I get to the preferences view. As for changing how the JSON is rendered, I'll have to look into it. It's currently using the default theme and json language files from vscode - and they aren't very fun to tweak
