### ISSUE TITLE
Add enhanced response viewers for binary/rich data types

### ISSUE THREAD

**Issue by DuffleOne** [getbeak/beak#64]
Type: Feature request
Platform: N/A

As a user, when I visit a URL that returns data such as an image, it'd be cool if Beak read the content-type header and showed the image rater then all the weird image data.

**Comment by 0xdeafcafe** [comment]
Yeah. Need much more rich and enhanced response viewers for binary data. I was thinking audio player, video player, photo viewer, and hex editor for binary data.

**Comment by 0xdeafcafe** [comment]
Half done - work is continuing
